# Generated by Django 4.2.7 on 2026-01-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentprofile_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio', models.FileField(upload_to='audio/stories/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='audio/stories/covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NatureSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nature', 'Природа'), ('city', 'Місто'), ('home', 'Дім'), ('transport', 'Транспорт')], default='nature', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio', models.FileField(upload_to='audio/sounds/')),
                ('icon', models.CharField(default='bi-volume-up', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title', 'id'],
            },
        ),
    ]
