# Generated by Django 4.2.7 on 2025-12-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentachievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='studentachievement',
            unique_together={('achievement', 'student')},
        ),
    ]
