# Generated by Django 4.2.7 on 2026-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gameresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('math', 'Math'), ('memory', 'Memory'), ('sound', 'Sound')], max_length=16),
        ),
    ]
