# Generated by Django 4.2.7 on 2026-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_gameresult_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(
                choices=[('math', 'Math'), ('memory', 'Memory'), ('sound', 'Sound'), ('words', 'Words')],
                max_length=16,
            ),
        ),
    ]
