# Generated by Django 4.2.7 on 2026-01-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_gameresult_game_type_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='specialists', to='accounts.childprofile'),
        ),
    ]
