# Generated by Django 4.2.7 on 2026-01-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_soundcard'),
        ('accounts', '0006_specialistprofile_students'),
    ]

    operations = []
