# Generated by Django 4.2.7 on 2026-01-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wordpuzzleword'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistStudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='accounts.specialistprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_notes', to='accounts.childprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
