# Generated by Django 4.2.7 on 2026-02-06 12:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_coloringpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloringpage',
            name='file',
            field=models.FileField(upload_to=accounts.models.UniqueUploadTo('coloring/pages')),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='audio',
            field=models.FileField(upload_to=accounts.models.UniqueUploadTo('sounds/audio')),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='image',
            field=models.ImageField(upload_to=accounts.models.UniqueUploadTo('sounds/images')),
        ),
        migrations.AlterField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.UniqueUploadTo('stories/audio')),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UniqueUploadTo('stories/images')),
        ),
        migrations.AlterField(
            model_name='story',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.UniqueUploadTo('stories/pdf')),
        ),
    ]
