# Generated by Django 4.2.7 on 2026-02-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_coloringpage_file_alter_soundcard_audio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childprofile',
            options={'verbose_name': 'Профіль дитини', 'verbose_name_plural': 'Профілі дітей'},
        ),
        migrations.AlterModelOptions(
            name='coloringpage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Розмальовка', 'verbose_name_plural': 'Розмальовки'},
        ),
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ['created_at'], 'verbose_name': 'Результат гри', 'verbose_name_plural': 'Результати ігор'},
        ),
        migrations.AlterModelOptions(
            name='sentenceexercise',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вправа з реченнями', 'verbose_name_plural': 'Вправи з реченнями'},
        ),
        migrations.AlterModelOptions(
            name='soundcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Картка звуку', 'verbose_name_plural': 'Картки звуків'},
        ),
        migrations.AlterModelOptions(
            name='specialistinvite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрошення спеціаліста', 'verbose_name_plural': 'Запрошення спеціалістів'},
        ),
        migrations.AlterModelOptions(
            name='specialistprofile',
            options={'verbose_name': 'Профіль спеціаліста', 'verbose_name_plural': 'Профілі спеціалістів'},
        ),
        migrations.AlterModelOptions(
            name='specialiststudentnote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Нотатка спеціаліста', 'verbose_name_plural': 'Нотатки спеціаліста'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at'], 'verbose_name': 'Казка', 'verbose_name_plural': 'Казки'},
        ),
        migrations.AlterModelOptions(
            name='storylisten',
            options={'ordering': ['-created_at'], 'verbose_name': 'Прослуховування казки', 'verbose_name_plural': 'Прослуховування казок'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-created_at'], 'verbose_name': 'Нагорода', 'verbose_name_plural': 'Нагороди'},
        ),
        migrations.AlterModelOptions(
            name='wordpuzzleword',
            options={'ordering': ['-created_at'], 'verbose_name': 'Слово пазлу', 'verbose_name_plural': 'Слова пазлів'},
        ),
    ]
