# Generated by Django 4.2.7 on 2026-02-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_childprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistprofile',
            name='coins',
        ),
    ]
