# Generated by Django 4.x on 2026-02-09

from django.conf import settings
from django.db import migrations, models
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_specialistprofile_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('instruction', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=accounts.models.UniqueUploadTo('articulation/images'))),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='articulation_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Артикуляційна вправа',
                'verbose_name_plural': 'Артикуляційні вправи',
                'ordering': ['-created_at'],
            },
        ),
    ]
