# Generated by Django 4.x on 2026-02-09

from django.conf import settings
from django.db import migrations, models
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_articulationcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=accounts.models.UniqueUploadTo('my_story/images'))),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='my_story_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Зображення для історії',
                'verbose_name_plural': 'Зображення для історій',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MyStoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='entries', to='accounts.mystoryimage')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='my_story_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Моя історія',
                'verbose_name_plural': 'Мої історії',
                'ordering': ['-created_at'],
            },
        ),
    ]
