# Generated by Django 4.x on 2026-02-09

from django.db import migrations, models
import django.db.models.deletion
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_my_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulationCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.UniqueUploadTo('articulation/images'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.articulationcard')),
            ],
            options={
                'verbose_name': 'Зображення для артикуляції',
                'verbose_name_plural': 'Зображення для артикуляції',
                'ordering': ['-created_at'],
            },
        ),
    ]
