# Generated by Django 4.x on 2026-02-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_articulation_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сценарій активності',
                'verbose_name_plural': 'Сценарії активностей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistActivityStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('task_text', models.CharField(max_length=220)),
                ('image', models.ImageField(upload_to=accounts.models.UniqueUploadTo('activities/images'))),
                ('audio', models.FileField(blank=True, null=True, upload_to=accounts.models.UniqueUploadTo('activities/audio'))),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.specialistactivity')),
            ],
            options={
                'verbose_name': 'Крок активності',
                'verbose_name_plural': 'Кроки активності',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
