# Generated by Django 4.2.7 on 2026-02-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_articulationcard_sounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('math', 'Math'), ('memory', 'Memory'), ('attention', 'Attention'), ('sound', 'Sound'), ('words', 'Words'), ('sentences', 'Sentences'), ('articulation', 'Articulation')], max_length=16),
        ),
    ]
