# Generated by Django 4.2.7 on 2026-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_gameresult_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='max_streak',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
